# Generated by Django 5.2.5 on 2025-08-10 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='first',
        ),
        migrations.RemoveField(
            model_name='message',
            name='last',
        ),
        migrations.AddField(
            model_name='message',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
