# Generated by Django 5.2.5 on 2025-08-11 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_message_first_remove_message_last_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='ips',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
