# Generated by Django 5.2.5 on 2025-08-11 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_posts_ips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='ips',
        ),
    ]
