# Generated by Django 5.2.5 on 2025-08-21 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_posts_ips'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='coment',
        ),
    ]
