# Generated by Django 5.2.5 on 2025-08-21 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_comment_comment_coment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='coment',
            new_name='message_comment',
        ),
    ]
