# Generated by Django 5.2.5 on 2025-08-21 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_coment_comment_message_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='message_comment',
            new_name='comment',
        ),
    ]
